# Generated by Django 3.0.2 on 2020-01-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20200106_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_on',
        ),
    ]
