# Generated by Django 3.0.2 on 2020-01-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_remove_userprofile_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipper',
        ),
    ]
