# Generated by Django 3.0.2 on 2020-01-07 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20200106_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper', models.IntegerField(blank=True, null=True)),
                ('client', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('time_submitted', models.DateTimeField()),
                ('time_expected', models.DateTimeField()),
                ('imgUrl', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=10)),
                ('onDelivery', models.CharField(max_length=5)),
                ('price_estimated', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('payment_method', models.CharField(max_length=50)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Laundry')),
            ],
        ),
        migrations.AddField(
            model_name='laundry',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Laundry')),
            ],
        ),
    ]
