# Generated by Django 3.0.2 on 2020-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20200107_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
    ]
