# Generated by Django 3.0.2 on 2020-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_auto_20200107_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='time_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
