# Generated by Django 3.0.2 on 2020-01-07 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_auto_20200107_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='agency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Shipper'),
        ),
    ]
