# Generated by Django 3.0.2 on 2020-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_auto_20200107_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='price_estimated',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
