# Generated by Django 3.0.2 on 2020-01-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0015_auto_20200114_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='agency',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='price_estimated',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='shipper',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Shipper'),
        ),
    ]
