# Generated by Django 3.0.2 on 2020-01-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_auto_20200114_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='price_estimated',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
