# Generated by Django 3.0.2 on 2020-01-14 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_auto_20200114_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='agency',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='client',
            field=models.ForeignKey(blank=True, default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='shipper',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.CASCADE, to='rest_api.Shipper'),
        ),
    ]
