# Generated by Django 3.0.2 on 2020-01-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_auto_20200116_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='price_estimated',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
