# Generated by Django 3.0.2 on 2020-01-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_auto_20200117_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
