# Generated by Django 3.0.2 on 2020-01-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_orderline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='laundry_key',
            field=models.IntegerField(default=0),
        ),
    ]
