# Generated by Django 3.0.2 on 2020-01-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_orderline_laundry_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='onDelivery',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
