# Generated by Django 3.0.2 on 2020-01-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_auto_20200131_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
