# Generated by Django 3.0.2 on 2020-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_auto_20200206_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
