# Generated by Django 3.0.2 on 2020-02-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0030_laundry_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
