# Generated by Django 3.0.2 on 2020-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0031_auto_20200207_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
