# Generated by Django 3.0.2 on 2020-02-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0032_auto_20200207_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='laundry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Laundry'),
        ),
    ]
