# Generated by Django 3.0.2 on 2020-02-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0033_auto_20200207_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='laundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Laundry', unique=True),
        ),
    ]
