# Generated by Django 3.0.2 on 2020-02-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0034_auto_20200207_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
